'use client'

import { Alert, Button, Card, Progress, Spinner } from 'flowbite-react'
import { useState } from 'react'
import { HiArrowLeft, HiArrowRight, HiCheck } from 'react-icons/hi'
import { useGraphCreation } from '../../task-monitoring/operationHooks'
import { customTheme } from '../../theme'
import { EntityInfoStep } from './steps/EntityInfoStep'
import { GenericGraphStep } from './steps/GenericGraphStep'
import { GraphTypeStep } from './steps/GraphTypeStep'
import { ReviewStep } from './steps/ReviewStep'
import { SchemaExtensionsStep } from './steps/SchemaExtensionsStep'
import { TierSelectionStep } from './steps/TierSelectionStep'
import type {
  EntityCreate,
  GraphCreationConfig,
  GraphCreationStep,
  GraphFormData,
} from './types'

interface GraphCreationWizardProps extends GraphCreationConfig {
  className?: string
}

/**
 * Entity graph creation wizard using the new operation-based monitoring
 */
export function GraphCreationWizard({
  allowGenericGraphs = true,
  requiredExtensions = [],
  showTierSelection = true,
  requireInitialEntity = false,
  validateEntity,
  onSuccess,
  onCancel,
  className = '',
}: GraphCreationWizardProps) {
  const graphCreation = useGraphCreation()

  const [currentStep, setCurrentStep] = useState(0)
  const [formData, setFormData] = useState<GraphFormData>({
    graphType: 'entity',
    entityName: '',
    entityDetails: undefined,
    createEntity: true, // Default to creating initial entity
    graphName: '', // For entity graphs without initial entity
    entityDescription: '', // Description for entity graphs
    entityTags: [], // Tags for entity graphs
    selectedExtensions: [...requiredExtensions],
    selectedTier: 'ladybug-standard',
    // Generic graph fields
    genericGraphName: '',
    genericGraphDescription: '',
    genericGraphTags: [],
    genericSchemaType: 'empty',
    genericCustomSchema: '',
  })

  // Define steps based on configuration and graph type
  const getSteps = (): GraphCreationStep[] => {
    const baseSteps: GraphCreationStep[] = []

    // Step 1: Graph Type (if allowed)
    if (allowGenericGraphs) {
      baseSteps.push({
        id: 'graph-type',
        title: 'Choose Graph Type',
        description: 'Select the type of graph database to create',
        validate: () => true,
      })
    }

    // Steps for entity graph
    if (formData.graphType === 'entity') {
      baseSteps.push(
        {
          id: 'entity-info',
          title: 'Entity Information',
          description: 'Enter the entity details',
          validate: (data) => {
            // If not creating entity, validate graph name instead
            if (!data.createEntity) {
              return !!(data.graphName && data.graphName.trim())
            }

            if (!data.entityName.trim()) return false
            if (validateEntity) {
              const error = validateEntity({
                name: data.entityName,
                uri: '', // URI will be auto-generated by backend
                ...data.entityDetails,
              })
              return !error
            }
            return true
          },
        },
        {
          id: 'schema-extensions',
          title: 'Schema Extensions',
          description: 'Select additional schema extensions',
          isOptional: true,
          validate: (data) => {
            // Ensure required extensions are included
            return requiredExtensions.every((ext) =>
              data.selectedExtensions.includes(ext)
            )
          },
        }
      )

      if (showTierSelection) {
        baseSteps.push({
          id: 'tier-selection',
          title: 'Select Tier',
          description: 'Choose the appropriate tier for your needs',
          validate: () => true,
        })
      }
    } else {
      // Steps for generic graph
      baseSteps.push({
        id: 'generic-graph',
        title: 'Graph Configuration',
        description: 'Configure your generic graph database',
        validate: (data) => {
          return !!data.genericGraphName.trim()
        },
      })
    }

    // Review step for all types
    baseSteps.push({
      id: 'review',
      title: 'Review & Create',
      description: 'Review your configuration and create the graph',
      validate: () => true,
    })

    return baseSteps
  }

  const steps = getSteps()
  const currentStepInfo = steps[currentStep]

  const handleNext = () => {
    if (currentStepInfo.validate && !currentStepInfo.validate(formData)) {
      return
    }
    if (currentStep < steps.length - 1) {
      setCurrentStep(currentStep + 1)
    }
  }

  const handleBack = () => {
    if (currentStep > 0) {
      setCurrentStep(currentStep - 1)
    }
  }

  const handleCreate = async () => {
    try {
      let result

      if (formData.graphType === 'entity') {
        // Create entity graph using new endpoint
        const graphName = formData.createEntity
          ? formData.entityName
          : formData.graphName || 'Empty Entity Graph'
        result = await graphCreation.createEntityGraph({
          entity_name: graphName,
          entity_identifier: formData.createEntity
            ? formData.entityDetails?.ein
            : undefined,
          entity_identifier_type:
            formData.createEntity && formData.entityDetails?.ein
              ? 'ein'
              : 'name',
          instance_tier: formData.selectedTier,
          schema_extensions: formData.selectedExtensions,
          create_entity: formData.createEntity,
          description: formData.entityDescription,
          tags: formData.entityTags,
        })
      } else {
        // Create generic graph
        result = await graphCreation.createGenericGraph({
          graph_name: formData.genericGraphName,
          description: formData.genericGraphDescription,
          instance_tier: formData.selectedTier,
          schema_extensions: formData.selectedExtensions,
        })
      }

      // Call success callback with full result
      if (onSuccess && result?.graph_id) {
        await onSuccess(result.graph_id, result)
      }
    } catch (error) {
      console.error('Failed to create graph:', error)
    }
  }

  // Render current step content
  const renderStepContent = () => {
    switch (currentStepInfo.id) {
      case 'graph-type':
        return (
          <GraphTypeStep
            selectedType={formData.graphType}
            onTypeChange={(type) =>
              setFormData({ ...formData, graphType: type })
            }
          />
        )
      case 'entity-info':
        return (
          <EntityInfoStep
            entityName={formData.entityName}
            entityDetails={formData.entityDetails}
            createEntity={formData.createEntity}
            graphName={formData.graphName}
            entityDescription={formData.entityDescription}
            entityTags={formData.entityTags}
            requireInitialEntity={requireInitialEntity}
            onUpdate={(updates) => setFormData({ ...formData, ...updates })}
            validationError={
              validateEntity && formData.entityName && formData.createEntity
                ? validateEntity({
                    // Required fields
                    name: formData.entityName,
                    uri: '', // URI will be auto-generated by backend
                    // Optional fields from entityDetails
                    ...formData.entityDetails,
                  } satisfies EntityCreate)
                : null
            }
          />
        )
      case 'schema-extensions':
        return (
          <SchemaExtensionsStep
            selectedExtensions={formData.selectedExtensions}
            requiredExtensions={requiredExtensions}
            onExtensionsChange={(extensions) =>
              setFormData({ ...formData, selectedExtensions: extensions })
            }
          />
        )
      case 'tier-selection':
        return (
          <TierSelectionStep
            selectedTier={formData.selectedTier}
            onTierChange={(tier) =>
              setFormData({ ...formData, selectedTier: tier })
            }
          />
        )
      case 'generic-graph':
        return (
          <GenericGraphStep
            graphName={formData.genericGraphName}
            description={formData.genericGraphDescription || ''}
            tags={formData.genericGraphTags}
            schemaType={formData.genericSchemaType}
            customSchema={formData.genericCustomSchema || ''}
            onGraphNameChange={(name) =>
              setFormData({ ...formData, genericGraphName: name })
            }
            onDescriptionChange={(desc) =>
              setFormData({ ...formData, genericGraphDescription: desc })
            }
            onTagsChange={(tags) =>
              setFormData({ ...formData, genericGraphTags: tags })
            }
            onSchemaTypeChange={(type) =>
              setFormData({ ...formData, genericSchemaType: type })
            }
            onCustomSchemaChange={(schema) =>
              setFormData({ ...formData, genericCustomSchema: schema })
            }
          />
        )
      case 'review':
        return <ReviewStep formData={formData} showTier={showTierSelection} />
      default:
        return null
    }
  }

  // Show creation progress when operation is running
  if (graphCreation.isLoading) {
    return (
      <Card theme={customTheme.card} className={className}>
        <div className="space-y-6">
          <div className="text-center">
            <h3 className="font-heading mb-2 text-xl font-bold tracking-tight text-gray-900 dark:text-white">
              Creating Your Graph Database
            </h3>
            <p className="text-gray-600 dark:text-gray-400">
              {graphCreation.currentStep || 'Initializing...'}
            </p>
          </div>

          <Progress
            progress={graphCreation.progress || 0}
            theme={customTheme.progress}
            size="lg"
            labelProgress
          />

          {graphCreation.operationId && (
            <p className="text-center text-sm text-gray-500 dark:text-gray-400">
              Operation ID: {graphCreation.operationId}
            </p>
          )}

          <div className="flex justify-center">
            <Button
              theme={customTheme.button}
              onClick={() => graphCreation.cancelOperation()}
              color="gray"
              size="sm"
            >
              Cancel
            </Button>
          </div>
        </div>
      </Card>
    )
  }

  // Show error state
  if (graphCreation.error) {
    return (
      <Card theme={customTheme.card} className={className}>
        <Alert theme={customTheme.alert} color="failure">
          <div className="space-y-2">
            <p className="font-semibold">Graph Creation Failed</p>
            <p>{graphCreation.error}</p>
            <div className="mt-4 flex gap-2">
              <Button
                theme={customTheme.button}
                onClick={() => graphCreation.reset()}
                size="sm"
                color="gray"
              >
                Try Again
              </Button>
              {onCancel && (
                <Button
                  theme={customTheme.button}
                  onClick={onCancel}
                  size="sm"
                  color="gray"
                  outline
                >
                  Cancel
                </Button>
              )}
            </div>
          </div>
        </Alert>
      </Card>
    )
  }

  // Show success state
  if (graphCreation.result && graphCreation.status === 'completed') {
    return (
      <Card theme={customTheme.card} className={className}>
        <div className="space-y-4 text-center">
          <div className="flex justify-center">
            <div className="rounded-full bg-green-100 p-3 dark:bg-green-900/30">
              <HiCheck className="h-8 w-8 text-green-600 dark:text-green-400" />
            </div>
          </div>
          <h3 className="font-heading text-xl font-bold tracking-tight text-gray-900 dark:text-white">
            Graph Created Successfully!
          </h3>
          <p className="text-gray-600 dark:text-gray-400">
            Your {formData.graphType} graph has been created and is ready to
            use.
          </p>
          {graphCreation.result.graph_id && (
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Graph ID:{' '}
              <code className="text-gray-700 dark:text-gray-300">
                {graphCreation.result.graph_id}
              </code>
            </p>
          )}
        </div>
      </Card>
    )
  }

  // Show wizard steps
  return (
    <Card theme={customTheme.card} className={className}>
      <div className="space-y-6">
        {/* Progress indicator */}
        <div className="mb-6 flex items-center justify-between">
          {steps.map((step, index) => (
            <div
              key={step.id}
              className={`flex items-center ${
                index < steps.length - 1 ? 'flex-1' : ''
              }`}
            >
              <div
                className={`flex h-10 w-10 items-center justify-center rounded-full border-2 transition-all ${
                  index < currentStep
                    ? 'border-blue-600 bg-blue-600 text-white dark:border-blue-500 dark:bg-blue-600'
                    : index === currentStep
                      ? 'border-blue-600 text-blue-600 dark:border-blue-500 dark:text-blue-400'
                      : 'border-gray-300 text-gray-400 dark:border-gray-600 dark:text-gray-500'
                }`}
              >
                {index < currentStep ? (
                  <HiCheck className="h-5 w-5" />
                ) : (
                  <span>{index + 1}</span>
                )}
              </div>
              {index < steps.length - 1 && (
                <div
                  className={`mx-2 h-0.5 flex-1 transition-all ${
                    index < currentStep
                      ? 'bg-blue-600 dark:bg-blue-500'
                      : 'bg-gray-300 dark:bg-gray-600'
                  }`}
                />
              )}
            </div>
          ))}
        </div>

        {/* Step content */}
        <div>
          <h3 className="font-heading mb-2 text-xl font-bold tracking-tight text-gray-900 dark:text-white">
            {currentStepInfo.title}
          </h3>
          <p className="mb-6 text-sm text-gray-500 dark:text-gray-400">
            {currentStepInfo.description}
          </p>
          {renderStepContent()}
        </div>

        {/* Navigation buttons */}
        <div className="flex justify-between">
          {currentStep > 0 ? (
            <Button
              theme={customTheme.button}
              onClick={handleBack}
              color="gray"
              outline
            >
              <HiArrowLeft className="mr-2 h-4 w-4" />
              Back
            </Button>
          ) : (
            <div />
          )}
          <div>
            {currentStep < steps.length - 1 ? (
              <Button
                theme={customTheme.button}
                onClick={handleNext}
                color="primary"
              >
                Next
                <HiArrowRight className="ml-2 h-4 w-4" />
              </Button>
            ) : (
              <Button
                theme={customTheme.button}
                onClick={handleCreate}
                color="success"
                disabled={graphCreation.isLoading}
              >
                {graphCreation.isLoading ? (
                  <>
                    <Spinner size="sm" className="mr-2" />
                    Creating...
                  </>
                ) : (
                  <>
                    Create Graph
                    <HiCheck className="ml-2 h-4 w-4" />
                  </>
                )}
              </Button>
            )}
          </div>
        </div>
      </div>
    </Card>
  )
}
